name: 'Build project'

on:
    push:
        branches:
            - main

jobs:
    checkout-code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
    build-solution:
        runs-on: ubuntu-latest
        needs: checkout-code
        steps:
            - uses: actions/setup-dotnet@latest
              with:
                  dotnet-version: '7.0.x'
            - name: Build solution
              run: dotnet build --configuration Release --no-restore