name: 'Build project'

on:
    push:
        branches:
            - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK 6.0.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.0
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal
  
